version: '3'

services:
  nextcloudplus:
    image: ownyourbits/nextcloudplus-armhf
    command: "192.168.1.200"
    ports:
     - "80:80"
     - "443:443"
     - "4443:4443"
    volumes:
     - ncdata:/data

volumes:
  ncdata:
